In [56]:
import pandas as pd

df = pd.read_csv('https://stats.moe.gov.tw/files/detail/111/111_student.csv')
df = df[['學校名稱', '總計']]
df['總計'] = df['總計'].str.replace(',', '')
df['總計'] = pd.to_numeric(df['總計'])
df = df.groupby('學校名稱').sum()

df = df.reset_index()

for i in df:
    print(i, end=' ')
print()

for i, j in zip(df['學校名稱'], df['總計']):
    print(i, j)

學校名稱 總計
世新大學 10899
中信金融管理學院 925
中原大學 16629
中國文化大學 22265
中國科技大學 7618
中國醫藥大學 7300
中山醫學大學 6982
中州科技大學 907
中臺科技大學 6921
中華大學 4461
中華科技大學 3886
中華醫事科技大學 7918
亞東科技大學 3921
亞洲大學 10913
仁德醫護管理專科學校 6156
佛光大學 3068
修平科技大學 4411
健行科技大學 10092
僑光科技大學 8900
元培醫事科技大學 5060
元智大學 8644
南亞技術學院 2320
南臺科技大學 16106
南華大學 5136
南開科技大學 2784
台北海洋科技大學 4007
台南應用科技大學 10720
台灣首府大學 337
吳鳳科技大學 4341
和春技術學院 69
嘉南藥理大學 10616
國立中央大學 12294
國立中山大學 10296
國立中正大學 11373
國立中興大學 15463
國立勤益科技大學 12421
國立嘉義大學 11486
國立宜蘭大學 5641
國立屏東大學 8922
國立屏東科技大學 10630
國立彰化師範大學 8526
國立成功大學 22825
國立政治大學 16727
國立暨南國際大學 6381
國立東華大學 10280
國立清華大學 18034
國立澎湖科技大學 2927
國立聯合大學 7649
國立臺中教育大學 5000
國立臺中科技大學 16095
國立臺北商業大學 7290
國立臺北大學 10277
國立臺北教育大學 5955
國立臺北科技大學 13633
國立臺北藝術大學 3179
國立臺北護理健康大學 5297
國立臺南大學 5869
國立臺南藝術大學 1662
國立臺南護理專科學校 1985
國立臺東大學 5099
國立臺東專科學校 755
國立臺灣大學 33422
國立臺灣師範大學 16262
國立臺灣戲曲學院 516
國立臺灣海洋大學 9167
國立臺灣科技大學 11648
國立臺灣藝術大學 5614
國立臺灣體育運動大學 3122
國立虎尾科技大學 11682
國立金門大學 4175
國立陽明交通大學 20707
國立雲林科技大學 10027
國立體育大學 2733
國立高雄大學 5986
國立高雄師範大學 7219
國立高雄科技大學 27848
國立高雄餐旅大學 4521
大仁科技大學 4522
大同大學 3818
大同技術學院 472
大漢技術學院 784
大葉大學 5694
宏國德霖科技大學 4689
實踐大學 11875
崇仁醫護管理專科學校 3051
崇右影藝科技大學 1364
崑山科技大學 9276
嶺東科技大學 9466
康寧大學 3192
建國科技大學 4796
弘光科技大學 12106
德明財經科技大學 6425
慈惠醫護管理專科學校 2748
慈濟大學 3057
慈濟科技大學 3022
敏實科技大學 563
敏惠醫護管理專科學校 3797
文藻外語大學 7930
新生醫護管理專科學校 5990
明志科技大學 4344
明新科技大學 10556
明道大學 1376
景文科技大學 5342
朝陽科技大學 13811
東南科技大學 4376
東吳大學 15287
東方設計大學 950
東海大學 15283
樹人醫護管理專科學校 7274
樹德科技大學 9131
正修科技大學 16767
法鼓文理學院 338
淡江大學 23328
玄奘大學 1805
環球科技大學 2111
真理大學 4314
經國管理暨健康學院 3659
美和科技大學 5502
義守大學 12941
耕莘健康管理專科學校 4214
聖母醫護管理專科學校 1636
聖約翰科技大學 1119
育英醫護管理專科學校 1891
育達科技大學 3434
致理科技大學 11326
臺北城市科技大學 8985
臺北市立大學 8031
臺北醫學大學 6154
華夏科技大學 2817
華梵大學 991
萬能科技大學 8223
輔仁大學 25981
輔英科技大學 9098
逢甲大學 21441
遠東科技大學 2932
醒吾科技大學 6687
銘傳大學 18256
長庚大學 6987
長庚科技大學 6271
長榮大學 6783
開南大學 4778
靜宜大學 11706
馬偕醫學院 862
馬偕醫護管理專科學校 4018
高苑科技大學 2105
高雄醫學大學 6518
黎明技術學院 5061
龍華科技大學 11720

In [ ]:
import pandas as pd

df = pd.read_csv('https://stats.moe.gov.tw/files/detail/111/111_student.csv')
df = df[['學校名稱', '總計']]
df['總計'] = df['總計'].str.replace(',', '')
df['總計'] = pd.to_numeric(df['總計'])
df = df.groupby('學校名稱').sum()

df = df.reset_index()

df.to_html('111大專校院校別學生數.html', index=False)